### ISSUE TITLE
Login Page Images

### ISSUE THREAD

**Issue by shebkhan** [mouneyrac/moodle-auth_googleoauth2#102]
Hi.

i have configured the plugin with oauth2 details still it is not displaying the login buttons.

can you please help

thanks

**Comment by mouneyrac** [comment]
Hi shebkhan, I answer there: https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/103
Cheers,
Jerome

**Comment by enlp** [comment]
hello . thanks for the update, but the buttons still are not shown at the bottom of the page, they are still being shown at the top, what to do ????

**Comment by mouneyrac** [comment]
I recommend to edit the php file of the login page and add the line indicated in the setting page.

**Comment by enlp** [comment]
cheerz :) yes you did but for a layman like me please guide how to do that as well :) gratitude

**Comment by mouneyrac** [comment]
http://www.youtube.com/watch?v=55gpCSnd1yU&t=14m30s there is the demo :)
