### ISSUE TITLE
Google sign-in doesn't work

### ISSUE THREAD

**Issue by fvendrell** [mouneyrac/moodle-auth_googleoauth2#106]
It seems that Google sign-in doesn't work.

I got the error message: "error/couldnotgetuseremail" when trying to sign-in after authentication with my Google account.

There is another similar comment on he page https://moodle.org/plugins/view/auth_googleoauth2

**Comment by mouneyrac** [comment]
Google still works (I checked on my test site)

Search for couldnotgetuseremail, maybe previous report may help: https://github.com/mouneyrac/moodle-auth_googleoauth2/issues?q=couldnotgetuseremail

Good luck.

**Comment by fvendrell** [comment]
Oups! I probably need a new pair of glasses!
Sorry with this inconvenience!
Your plugin works very well and thank you very much!
