### ISSUE TITLE
Linked-in sign-in: "OAuth 1.0 Accept Redirect URL:"

### ISSUE THREAD

**Issue by fvendrell** [mouneyrac/moodle-auth_googleoauth2#107]
On the setting page, the text:
"OAuth 1.0 Accept Redirect URL"
should be replaced by
"OAuth 2.0 Accept Redirect URL:"

I tried with 1.0 and since it didn't work, I tried with 2.0 and it did work!

**Comment by mouneyrac** [comment]
fixed, thanks for the report.
