### ISSUE TITLE
moodle 2.8.2 with facebook authentication?

### ISSUE THREAD

**Issue by park305** [mouneyrac/moodle-auth_googleoauth2#108]
Getting this error when a new use tries to register/login with Facebook:

The authentication provider sent us a communication error. Please try to sign-in again.

I'm using version moodle 2.8.2 verified the app id and secret are correct. Guessing it's not compatible?

**Comment by park305** [comment]
I turned on debugging for the site and got a more detailed error. Looks like it's oddly grabbing a ip v6 and unable to connect.

Debug info: Failed to connect to 2a03:2880:2110:9f07:face:b00c:0:1: Network is unreachable
Error code: couldnotgetgoogleaccesstoken

Stack trace: •line 436 of /auth/googleoauth2/auth.php: moodle_exception thrown
•line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

Output buffer: <br /> <b>Notice</b>: Undefined index: access_token in <b>/home2/mindfuo8/public_html/teaching/auth/googleoauth2/auth.php</b> on line <b>171</b><br />

**Comment by mouneyrac** [comment]
It does look odd to me too. I don't think it is related to the plugin itself though. It's probably a problem on facebook side or on your side or somewhere in the middle. I let this issue open a while if ever someone else wants to comment on this.

**Comment by park305** [comment]
I think it's likely the bluehost that's causing this error because they're blocking the connection. I never got an official reply about this from them but seems most likely.
