### ISSUE TITLE
Sign-in with Google is not shown on Firefox

### ISSUE THREAD

**Issue by danielneis** [mouneyrac/moodle-auth_googleoauth2#112]
Hello,

i am using Firefox 37.0.1 and the "Sign-in with Google" is not shown,
altough it is correctly configured and the facebook button works.
I've tried with Chromium and it is working well.
The problem is the same if I am logged in or out of google account,
using a private or normal window.
Also, I've tested on two different Moodle sites.

**Comment by mouneyrac** [comment]
Hi Daniel, do you still have the issue?
I confirm that I can see it on 37.0.2 (http://bepaw.com/login/)

**Comment by danielneis** [comment]
In fact, it is being blocked by adblock plus, sorry for the wrong report.
Is this still an issue? Facebook, battle.net and VK is shown even with adblock enabled.

**Comment by mouneyrac** [comment]
All good then. It's always good to have an explanation so if someone use adblock and have this issue he can try to disable it. Thanks Daniel. Closing.
