### ISSUE TITLE
couldnotauthenticateuserlogin

### ISSUE THREAD

**Issue by jhingvp** [mouneyrac/moodle-auth_googleoauth2#127]
Thank you for this plugin Jerome.

I am building up a Moodle site for my class wishing to have a Google authentication integrated on it.

What I have done.

Downloaded your plugin here: http://mouneyrac.github.io/moodle-auth_googleoauth2/
Extracted the content
Created a folder inside auth: googleoauth2
Uploaded all the extracted file via ftp inside googleauth2 of the live moodle site (Login Page)
![image](https://cloud.githubusercontent.com/assets/12905201/8175237/f598bfe8-1419-11e5-87a1-048192b1d8e3.png)

After clicking the log in, I got this error: error/auth googleoauth2/couldnotauthenticateuserlogin
![image](https://cloud.githubusercontent.com/assets/12905201/8175245/1703a72e-141a-11e5-91ac-54754baf5082.png)

Configurations that I have set already:
Google+ API Enabled:
![image](https://cloud.githubusercontent.com/assets/12905201/8175267/5dfcefaa-141a-11e5-8a0d-c80dc7ccf7de.png)

OAuth2 already enabled and installed in moodle site:
![image](https://cloud.githubusercontent.com/assets/12905201/8175280/a528e348-141a-11e5-8783-c7661173805d.png)

What could be my error? Thanks for the help.

**Comment by mouneyrac** [comment]
is it because you already have a user with the same email address? https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/79

**Comment by jhingvp** [comment]
Okay, should I disable other authentication methods? in Moodle?

**Comment by jhingvp** [comment]
Sorry I didn't get it, so, If I have that user already, logging in my Moodle site will require me or other users to type in the User & Login Box? Not use the Google Sign-in Button?

**Comment by mouneyrac** [comment]
if someone login with 2 different authentication method, then he will have 2 different accounts. When I created the plugin I just wanted to use this plugin. However I'll likely implement a solution for accepting login on other email as people request it.

**Comment by jhingvp** [comment]
So now, I have two concerns:

1) How will I disable the default Manual Authentication?

2) I have tried logging in with non-existent google account account, I got this error message:
![image](https://cloud.githubusercontent.com/assets/12905201/8175738/735c1f5e-1421-11e5-8cab-20e4506eb247.png)

**Comment by mouneyrac** [comment]
1) I use css, so you don't disable it, you hide it. Which is what you want so you can still connect with administrator.

2) did you set the prevent user creation on?

**Comment by jhingvp** [comment]
1) That's a very good workaround! Is it available together with the zipped file of the plugin? I am weak in CSS but I can do it given a guide.

Nope, it's still on the Default. So the way I understand it, is that, users will be automatically created once they logged in if they do not exist in the Moodle users database.

**Comment by mouneyrac** [comment]
yes :)

**Comment by jhingvp** [comment]
Thank you very much Jerome @mouneyrac. My understanding on the #2 topic above is correct but the setting of the option is not clear to me, I tried to uncheck the default option of "prevent user creation" and IT WORKS! I can't thank you enough for your prompt reply and attention. We will be watching updates from your plugin. :+1:

**Comment by mouneyrac** [comment]
no problem, you can add it to your favorites on Moodle.org page and star it on github, it's always nice to see these number bumping :) have fun with the plugin.
