### ISSUE TITLE
Translation of the exceptions

### ISSUE THREAD

**Issue by chnicolas** [mouneyrac/moodle-auth_googleoauth2#135]
I noticed that exceptions are used in the code.
I suggest you use $module parameter when you throw moodle_exception.
For translation, it's easier.
For ex : 
    throw new moodle_exception('couldnotgetuseremail','auth_googleoauth2');
Instead of :
    throw new moodle_exception('couldnotgetuseremail');
Thus, the translation is not taken into account for following error codes : unknown_oauth2_provider, couldnotgetuseremail, facebook_failure, google_failure, linkedin_failure...

**Comment by mouneyrac** [comment]
Thanks for the report Charlotte (I suppose it's you).

**Comment by mouneyrac** [comment]
done
