### ISSUE TITLE
auth_googleoauth2 plugin English language strings not available for translation in AMOS for some branches

### ISSUE THREAD

**Issue by germanvaleroelizondo** [mouneyrac/moodle-auth_googleoauth2#138]
Hi,
Even though the auth_googleoauth2 plugin is available for download for many Moodle branches, AMOS (https://lang.moodle.org/local/amos/) only has 2.1 to 2.5 branches available for translation of its English language strings. Moodle branches 2.6 to 2.9 do not have the English language strings available for translation in AMOS :(

Being that this plugin is the most downloaded auth plugin for Moodle (see https://moodle.org/plugins/stats.php?plugin_category=21) , I think this is an important issue.

In other plugins, the lack of branches available for translation was caused by a coding error, which was spotted by David Mudrak.

Thanks in advance for your help.

**Comment by mouneyrac** [comment]
Hello,
Thanks for your report. Even thought I love it, I have very little time at the moment to work on the plugin. You are welcome to help me thought. Does the plugin maintainer need to do any actions in Amos or can you contribute yourself directly? I don't know it (check the Amos doc for me if you have time too), it is a genuine question. Let me know the steps I need to do in amos to allow people to contribute. 
Cheers,
Jerome

**Comment by germanvaleroelizondo** [comment]
Hello,
Thanks for your quick response.

The processing of English language strings by AMOS is automatic.

The plugin maintainer might want to check his code with codechecker (https://moodle.org/plugins/view/local_codechecker ) or some other tool (sorry, I am not a programmer but  a veterinarian who helps to translate moodle into spanish).

If no obvious problem is seen (in the past many English strings translation problems were caused by string concatenation in the plugin code), maybe we should seek help from David Mudrak. Even though he has other tasks at Moodle HQ and he is not officially bound to help third party plugins, I would guess he might be extremely interested because of the very high number of users for this particular plugin.

Please see https://lang.moodle.org/mod/forum/discuss.php?d=2691 for examples of previous English language strings problems at AMOS, their causes and fixes.

I'd really love to have this greatly successful  useful plugin available for translation.

**Comment by mouneyrac** [comment]
Hi germanvaleroelizondo,
I quickly read https://docs.moodle.org/dev/Translating_plugins, it looks like the branch should appear automatically in Amos and if they don't it's because there maybe some errors in the lang file (i.e. what you mentioned). I will check these files later when I have some free time. Thanks again for your report.

**Comment by germanvaleroelizondo** [comment]
Hi,

I hope the information at https://docs.moodle.org/dev/Translating_plugins#Plugins_with_coding_errors helps you to identify the error causing the problem, but if it turns out to be some other error, I think it would be wise to update the documentation details to help other plugin developers.

Thanks again. 

Good luck with the error hunting. 

I'll be looking forward to translating your plugin for  the newer Moodle branches

**Comment by mouneyrac** [comment]
Note: I fixed all codechecker errors on the master branch.

**Comment by mouneyrac** [comment]
I think I found out, there is a concatenation in the lang string auth_googleoauth2description. I will fix it in master, but master need thourough testing before to be sent on Moodle.org repository. Master code is very different from the version currently downloadable on Moodle.org.

**Comment by mouneyrac** [comment]
Fixed, hopefully it will work next upload.

**Comment by mouneyrac** [comment]
it is now fixed :) No AMOS error during upload anymore and AMOS found 51 new strings for 2.7/2.8/2.9 :)

**Comment by mouneyrac** [comment]
If you like that favorites the plugin on the Moodle.org plugin page / Stargaze the plugin on github :) Cheers and thanks :)

**Comment by germanvaleroelizondo** [comment]
Hi Jérôme,

Thanks for providing the fixes.

I have starred this plugin in Github and added it to my Moodle favorite plugins :)

But I noticed that the plugin version for Moodle 2.6 is a different file and it does not have any English language strings available for translation in AMOS. Will you be able to fix this version in the future?

Thanks in advance for your help.
