### ISSUE TITLE
osTicket OAuth

### ISSUE THREAD

**Issue by jhingvp** [mouneyrac/moodle-auth_googleoauth2#139]
Good day Jerome!

Just a query, have anybody tried implementing OAuth in osTicket? Or are you familiar on how we can implement it on osTicket? currently there's no Google OAuth plugin in their repo, only LDAP and Amazon S3 and others? I am planning to have the same auth method in may helpdesk/support site. Any idea on this? Thanks much!

**Comment by mouneyrac** [comment]
Hi jhingvp,
I hope I am not wrong closing your issue. It is not related to Moodle oauth2 plugin. Try stackoverflow it is designed to ask generic question. Maybe is there a forum in osticket you could try too? I hope you will find your answer. Cheers, jerome

**Comment by jhingvp** [comment]
Sorry for the late reply Jerome. Thank you.

*jacinto "jhing" valera*
pena street, brgy. 3
san jose, antique
09277637667 | jhing.vp@gmail.com
+63365438161 local 113 | jacinto.valera@antiquespride.edu.ph
