### ISSUE TITLE
Failed Login 'auth_googleoauth2\event\user_loggedin' 

### ISSUE THREAD

**Issue by jstuckey698** [mouneyrac/moodle-auth_googleoauth2#147]
Hello, 

I've implemented the plugin and have the user authenticating but when I login with a google account, I go to a white screen and nothing is displayed. A refresh takes the user to the homepage but during debugging I found this error code:

Fatal error: Class 'auth_googleoauth2\event\user_loggedin' not found in /usr/libexec/siteaddressmoodle/auth/googleoauth2/auth.php on line 403

Moodle version: Moodle 2.6.11 (Build: 20150511)
Plugin Build Version 1.5: 2014111902

Thoughts or suggestions?

Thank you,

Josh

**Comment by mouneyrac** [comment]
it could be that you are matching the wrong version of Moodle with the wrong version of the plugin. Where did you get your plugin version?Moodle.org? Gihub? If Github, did you take STABLE_26 branch? I

**Comment by jstuckey698** [comment]
Hello Jerome,

I got the plugin from here: https://moodle.org/plugins/view/auth_googleoauth2
<https://moodle.org/plugins/pluginversion.php?id=7384>
Release *1.5 (Build: 2014111902) STABLE_26*
<https://moodle.org/plugins/pluginversion.php?id=7384>

Thoughts of what might be causing that error?


*Thank you,*

*Josh Stuckey*
*Software Systems Analyst*
Information Technology
Olds College

*Phone:* 403-507-7919
*www.oldscollege.ca <http://www.oldscollege.ca/>*
<http://www.oldscollege.ca/>

<http://www.oldscollege.ca/>*[image: Olds College]
<http://www.oldscollege.ca/>*

**Comment by mouneyrac** [comment]
Things I can think of:
* wrong permission of the plugin files (especially classes/event)
* problem during upgrade from 2.5 to 2.6
* php version not supporting \...\... namespace

**Comment by mouneyrac** [comment]
I guess we can close this issue as there are no activities anymore. Let us know if you find out what could be your issue, it may help other people with the same problem. Thanks.
