### ISSUE TITLE
Manual Button Display Shows Twice On Home Page

### ISSUE THREAD

**Issue by majedian21** [mouneyrac/moodle-auth_googleoauth2#148]
Moodle version: 2.9.1 (stable release)
Server: CentOS 7

I am trying to manually set the Google sign-in button by modifying the block_login.php file in Moodle (see below). However, when I do this, it shows the 'Sign-in with Google' link both where I expect it to go and also (unexpectedly) at the very top of the page (even above the <title>...</title> line). How do I disable this second, duplicate link showing at the top of the home page?

vi <moodleHome>/blocks/login/block_login.php
....
require_once($CFG->dirroot . '/auth/googleoauth2/lib.php');
....
$this->content->text .= '<div>';
$this->content->text .= auth_googleoauth2_display_buttons();
$this->content->text .= '</div>';

**Comment by mouneyrac** [comment]
did you disable/uncheck the default buttons in the setting page?

**Comment by mouneyrac** [comment]
Closing the issue as no feedback.
