### ISSUE TITLE
Authentication plugin googleoauth2 not found

### ISSUE THREAD

**Issue by Mohammed-Zayan** [mouneyrac/moodle-auth_googleoauth2#153]
Hello there,
I install the plugin from here
https://moodle.org/plugins/view/auth_googleoauth2
Release 2.0 (Build: 2015051504)
Moodle 2.7, 2.8, 2.9

I use moodle 2.9
when I go to Admin block > Plugins > Authentication > Manage authentication
I have this error
Authentication plugin googleoauth2 not found.
More information about this error
I go to more information page 
https://docs.moodle.org/29/en/error/debug/authpluginnotfound

I didn't found settings.php file

**Comment by mouneyrac** [comment]
can you check you have the plugin files in auth/googleoauth2 ?

**Comment by Mohammed-Zayan** [comment]
Yes I have.
I solve the problem it was a permissions problem.

Thank you,  mouneyrac.

**Comment by mouneyrac** [comment]
No problem, happy it works well for you. If you have time, favorite the plugin on the Moodle.org page, it is always motivating for me to keep going to maintain the plugin and answering people questions/issues:  https://moodle.org/plugins/view/auth_googleoauth2

thanks :)
