### ISSUE TITLE
Buttons are not showing (except for midori browser) ¿?

### ISSUE THREAD

**Issue by ermengolbota** [mouneyrac/moodle-auth_googleoauth2#164]
It's a little bit strange but, the google login buttons (or FB or...) are not showing up on the login screen....but it "only" happens with Firefox, Chrome, Chromium.....but with Midori browser works fine ¿?¿?¿?

We are using the latest plugin (2.1 (Build: 2015090200) ), with the "Clean" theme (and "More" theme also), on Moodle 2.9.1+ (Build: 20150903)

We haven't tried yet to manually insert the php code for the login buttons on login page, we'll try to do it on monday.

Midori browser uses webkit render engine (as chrome), and it shows the login button.

Any help will be appreciate.

You can check our login page at https://campus.iam.cat/moodle/login/index.php

**Comment by ermengolbota** [comment]
Solved (or at least there is a workaround)
The problem was solved by changing the login page to a non secure, instead of https that we were using.
Once we've changed this, all the browsers work fine.
Hopefully, nobody is using the basic authentication method ....the password will travel in plain text!!!

**Comment by mouneyrac** [comment]
thanks for reporting the solution Ermengol. I'll open an issue to do some check about the site running on https

**Comment by spinozarabel** [comment]
Hello,
Thanks for your wonderful work and great attitude. I am very grateful for your time.
I have same problem that the buttons don't show on the login page and I am using https. I also have regular login and so cannot change to http. I am using your version 2.2 and moodle 3.01+. Is this fixed yet? If not kindly suggest how I can get this to work.

Kind regards,

Madhu
