### ISSUE TITLE
User not logged in after authenticating...

### ISSUE THREAD

**Issue by wmclaa** [mouneyrac/moodle-auth_googleoauth2#167]
We have had the Moodle oAuth 2.0 plugin running for about 10 months with no problem.  Today, 9/23/2015 I updated the plugin and since then, no users can login with Google.

1.  Users select the "Google" login button.
2.  Users are brought to the Google consent screen.
3.  Users return to the LMS...but are not logged in.

This is obviously urgent...

Thank you,
William Michael
Classical Liberal Arts Academy

**Comment by mouneyrac** [comment]
we don't have enough info to reproduce the problem. If anyone else is having issue after upgrading please open a new issue and give your previous version.php content so we can test the upgrade process. 

As a workaround, Michael said by email: "I decided to go for it, backed up the database and deleted the plugin folder.  I then reinstalled the newest version of the plugin and that was it."

**Comment by mouneyrac** [comment]
As I mentioned in https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/168 I believe there is not problem with the upgrade. It is likely a mess up in your file permission when you upgrade from Moodle.org plugin repsoitory. The fact that just deleting the file worked confirm it too.
