### ISSUE TITLE
You do not have permission to use the site yet

### ISSUE THREAD

**Issue by zayanit** [mouneyrac/moodle-auth_googleoauth2#170]
The user can use the plugin after he/she login using the plugin this message appear

You do not have permission to use the site yet. Please contact your administrator and ask them to activate your account.

**Comment by mouneyrac** [comment]
Hi Mohammed,
did you resolve the issue? does your site allow Moodle account creation (authpreventaccountcreation admin setting) ?

**Comment by zayanit** [comment]
Unfortunately I have used another plugin for other reasons

**Comment by mouneyrac** [comment]
No problem, which plugin are you using? For which reasons?

**Comment by mouneyrac** [comment]
Closing the issue, thanks for the report.
