### ISSUE TITLE
Got problem after installing plug-in in moodle2.9.1

### ISSUE THREAD

**Issue by Santi87** [mouneyrac/moodle-auth_googleoauth2#171]
Hello, I have the following problem in my moodle 2.9.1 platform , my platform was functioning common and current , when I got the idea of ​​installing this plug-in.

When I Installed the plug -in  and  it is finished,  the website goes to: my_url/admin/index.php and can't get loaded !!!! Also whenever moodle income , there is routed automatically to my_url/admin/index.php and the page isn't loaded again !!!  I Looked for another  ways to remove the extension  but not where it is ?? .... someone could help me please ??

**Comment by Santi87** [comment]
This is de video: https://www.youtube.com/watch?t=7&v=i5AgabY-Rjs

Someone can help me??

**Comment by GitRaams** [comment]
Hi Santi87

In Moodle - user creation page ... below the "username" field, there is an option 
"Choose an authentication method" --> Manual accounts.

Change this value to "Oauth2".
Make sure, username and email-id fields are the same.

It works great now. Thanks to everyone for everything.

GitRaams!

**Comment by mouneyrac** [comment]
Thanks for posting the solution GitRaams.
