### ISSUE TITLE
I could not connect to facebook

### ISSUE THREAD

**Issue by ceremy1** [mouneyrac/moodle-auth_googleoauth2#172]
i get error like 
![sorun1](https://cloud.githubusercontent.com/assets/13921682/10524773/ecef562a-7389-11e5-9c5e-af712f692ae9.jpg)

my facebook's setting 
![sorun](https://cloud.githubusercontent.com/assets/13921682/10524798/0d461b2a-738a-11e5-94af-4bc52efae6f3.jpg)

**Comment by mouneyrac** [comment]
someone already use this email address and multiple auth support is not implemented yet.

**Comment by ceremy1** [comment]
i see, thanks mouneyrac for reply
