### ISSUE TITLE
Missing closing div in auth_googleoauth2_render_buttons()

### ISSUE THREAD

**Issue by simonvart** [mouneyrac/moodle-auth_googleoauth2#176]
Hi,

I think you are missing a closing <div> in the lib.php

 Line 139 : `$html .= "<div>";`
 [...]
 Line 175 : `return $html;`

If you check the DOM when using  `auth_googleoauth2_display_buttons()`, you'll see that the closing `</div>` is missing, and the result could be messy.

I propose a very simple correction : 

Line 175: `return $html  . '</div>';`

**Comment by mouneyrac** [comment]
done thanks Simon.
