### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by ewallah** [mouneyrac/moodle-auth_googleoauth2#183]
Even when the plugin is not enabled, the authentication method writes log entries with no respect for the debugging  settings:
error_log(print_r($event, true));
error_log(print_r($event->userid, true));
This should be documented in the readme file, and should only happen when debugging is enabled.

**Comment by mouneyrac** [comment]
thanks for the report, if you can send a pull request that remove these two lines I'll be happy to integrate it :)

**Comment by mouneyrac** [comment]
done, thanks for the report.
