### ISSUE TITLE
couldnotgetuseremail - Facebook connect error

### ISSUE THREAD

**Issue by Ankhesa** [mouneyrac/moodle-auth_googleoauth2#196]
Hi all! We get this error: auth_googleoauth2/couldnotgetuseremail

More information about this error
Debug info:
Error code: couldnotgetuseremail
$a contents:
Stack trace:

line 190 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

This happen when trying to connect with facebook

Moodle version: 2.9.4
Plugin version: 
$plugin->version  = 2015110600;
$plugin->release = '2.2 (Build: 2015110600)';

Could you please help me? It would be apprecited, I've spent too many hours around this problem 

Thanks!

**Comment by mouneyrac** [comment]
Hi Ankhesa I would suggest to search couldnotgetuseremail in the previous issue. I tested facebook it still works, it is likely you are having the same issue that everybody else: https://github.com/mouneyrac/moodle-auth_googleoauth2/issues?utf8=%E2%9C%93&q=couldnotgetuseremail

I am closing this issue as it is likely resolved by Ankhesa or similar to previous issue reports (misconfiguration).

Feel free to comment/reopen if necessary.
