### ISSUE TITLE
Restrict to a single domain

### ISSUE THREAD

**Issue by dadiletta** [mouneyrac/moodle-auth_googleoauth2#198]
I'm trying to do something like [this](http://stackoverflow.com/questions/10858813/restrict-login-email-with-google-oauth2-0-to-specific-domain-name) where only my school's domain is allowed to use the Google login. I've been combing through the code to find where I might add this but can't figure it out. Any help?

**Comment by atainton** [comment]
Moodle already has a option for this on this page /admin/settings.php?section=manageauths if you scroll down

**Comment by dadiletta** [comment]
You're right, works like a charm!
