### ISSUE TITLE
vendor/autoload.php missing from repo

### ISSUE THREAD

**Issue by atainton** [mouneyrac/moodle-auth_googleoauth2#199]
I am getting a failed to open stream: No such file or directory for vendor/autoload.php.

I see this isnt in the repo but how does it get loaded in.

**Comment by Jarvil** [comment]
Hello,

Has this been fixed yet?

**Comment by atainton** [comment]
Nope, i still have the error

**Comment by trile85** [comment]
You need to install composer then run
composer install
or php composer.phar install

**Comment by mouneyrac** [comment]
Thanks trile85 :) I mark this issue as close.

Btw I created a free mini-course to install a plugin: http://bepaw-open-source-school.teachable.com/courses/how-to-install-a-plugin

**Comment by Trynes** [comment]
I tried php composer.phar install and it gave me this message in return: Composer could not find a composer.json file in /moodle/auth/googleoauth2
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

What exactly would I put in the composer.json file?
