### ISSUE TITLE
Question about Google and ID Number

### ISSUE THREAD

**Issue by jtsafran** [mouneyrac/moodle-auth_googleoauth2#202]
Does the Google integration pull in an ID Number?  I have been trying to figure out what field it might be attached to, but I have had no luck.

Thanks!

**Comment by mouneyrac** [comment]
user email are identifiers. It is probably enough for your use case but if it is not then search for cansaveaccesstoken in auth.php. You'll need to add the correct config key/value in Moodle DB, the the plugin will fill up the auth_googleoauth2_user_idps table. It was some code I added to be able to deal with providers API beyond authentication. However by security purpose it is disabled and hidden.

**Comment by jtsafran** [comment]
Jerome,

Thank you for getting back to me and for developing and maintaining the plugin!

Just to clarify, by default, the only fields that I will see populated in Moodle when authenticating against Google are the First Name, Last name, and email address?  Any others?

Thanks, again!
-Jesse

**Comment by mouneyrac** [comment]
From memory you have country/city too.
