### ISSUE TITLE
Upgrading to 3.1 failing - Table "auth_googleoauth2_user_idps" does not exist

### ISSUE THREAD

**Issue by sheila888** [mouneyrac/moodle-auth_googleoauth2#205]
Hi Jerome

I have been getting this message:

Table "auth_googleoauth2_user_idps" does not exist

when I've been trying to upgrade to the new version for 3.1.

Any suggestions would be gratefully received.

We are on Moodle 3.1.

Here is the error when upgrading:

Debug info: 
Error code: ddltablenotexist

Stack trace:
line 582 of /lib/ddl/database_manager.php: ddl_table_missing_exception thrown
line 87 of /auth/googleoauth2/db/upgrade.php: call to database_manager->change_field_type()
line 552 of /lib/upgradelib.php: call to xmldb_auth_googleoauth2_upgrade()
line 1742 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

Many thanks.

Sheila

**Comment by mouneyrac** [comment]
Hi, looks like you have a mess up db. Could be a plugin bug upgrade but it is more likely that you did something wrong with your Moodle DB / plugin version number as the code seems to have miss the upgrade of the table.

A solution is to uninstall and reinstall the plugin (backing up your site and all normal procedures)

**Comment by sheila888** [comment]
Hi Jerome

Thank you so much for the quick reply.  I can't uninstall it as there is no uninstall option.  It seems to think that I have the latest version installed but it keeps asking me to reinstall it.  Any quick backend fix to the database you can suggest?

Best regards

Sheila

**Comment by mouneyrac** [comment]
Hum how that it keeps asking you to reinstall? If it is the case then it
means that you never finish the upgrade and so you error would make sense
as it never install the table.

**Comment by sheila888** [comment]
Hi Jerome - I deleted the config_plugin files and managed to get it working.  Great plugin - been using it for a very long time now.  Thanks again.  Best regards Sheila

**Comment by mouneyrac** [comment]
Super, I am happy it works well and thanks for the compliment and the solution. Closing the issue thanks.
