### ISSUE TITLE
Loggedin users can still see courses that are in hidden categories

### ISSUE THREAD

**Issue by zmuslat** [mouneyrac/moodle-auth_googleoauth2#207]
We use hidden categories to control who can see live courses. The issue is for students that are added in moodle manually, they would not see a course in a hidden category unless they are enrolled the course. However, users who are using this plugin can see these courses (though they cannot enroll), but we want them to not be able to see these courses completely. 

Our site assigns the "Authenticated user at front page" to all users by default, but this does not seem to be applied to the social users.

Can you pleas provide insights on how this issue can be resolved.

**Comment by mouneyrac** [comment]
Authentication plugins have no impact on the fact that you see or not see a category/course. As you say you manually add user in Moodle, you must do something that obviously the auth_googleoauth2 plugin doesn't do by default (i.e. all the enrol/role/persmission that that allow your manually added user to be enrolled and no see the hidden category)

I will close this issue as I am pretty sure it is not related to auth_googleoauth2.

Feel free to reopen if you discover it is actually related.

Cheers,
Jerome
