### ISSUE TITLE
dropbox_redirect.php file missing from package

### ISSUE THREAD

**Issue by dlboggs** [mouneyrac/moodle-auth_googleoauth2#215]
I am not finding the dropbox_redirect.php file in the googleauth2 folder.  Am I looking in the wrong place?

**Comment by mouneyrac** [comment]
Hi dlboggs,
it is likely that you are looking to wrong place or do not have a version of the plugin including Dropbox. You can see it is there: https://github.com/mouneyrac/moodle-auth_googleoauth2/blob/master/dropbox_redirect.php
cheers,
Jerome

**Comment by mouneyrac** [comment]
I am closing this issue as I don't think it is missing from the plugin versions including dropbox.
Thanks for the report. Feel free to still comment on it :)
cheers,
Jerome
