### ISSUE TITLE
Debug info:  Error code: faileduserdetails on Facebook

### ISSUE THREAD

**Issue by joetha** [mouneyrac/moodle-auth_googleoauth2#218]
I have a Moodleinstallation:

Moodle 3.1+ (Build: 20160623)
with
Oauth2 auth_googleoauth2 2.3 (Build: 2016061200)

on a contabo VPS CentOS 7.x

When Google login everything is ok.
When Facebook Login brings Moodle following errors in DebuggerModus:

Debug info: 
Error code: faileduserdetails
Stack trace:
line 178 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 90 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

In developers.facebook.com:
The app is on Facebook not in development mode!
A valid OAuth Redirect URIs is registered.
API-Version v2.8

When user account from Facebook users:
Apps, websites and plugins is active in the Facebook account.
The app is detected even at Facebook and Apps.

Where is my mistake. Please help me!

**Comment by cthemudo** [comment]
Hello, I have the same problem

Versión de Moodle
2016052302
Revisión de Moodle
3.1.2 (Build: 20160912)

Extension: Oauth2 auth_googleoauth2
2.2 (Build: 2015110600)
2015110600

When Google login everything is ok.
When LinkedIn login everything is ok.

When Facebook Login brings Moodle following errors:
"The site succeed to connect to the selected provider but failed to retrieve your user details. If you are using Google, check that your site administrator has enabled the Google+ API in the Google developer console. It is the most common reason for this error."

In developers.facebook.com:
The app is on Facebook not in development mode!
A valid OAuth Redirect URIs is registered.
API-Version v2.8
"Require App Secret" is set to "No" in facebook app > advanced settings (with "Yes" fails too)

Any idea? Thank you!

**Comment by mouneyrac** [comment]
I confirm Facebook is not working anymore for newly created API key - it still works for people having previously set it. I added some warning in the settings page - as this is a duplicated of https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/219 I am closing the issue.
