### ISSUE TITLE
[CRITICAL] Bug login  with Facebook API v2.8

### ISSUE THREAD

**Issue by denver89** [mouneyrac/moodle-auth_googleoauth2#219]
I implemented the plugin with Facebook and Google+, everything worked perfectly until Facebook released the v2.8 API.

With the v2.8 API, the authentification with Facebook goes wrong.

This is the error message :
 The site succeed to connect to the selected provider but failed to retrieve your user details.

Debug info: 
Error code: faileduserdetails

Stack trace:
line 175 of /auth/googleoauth2/auth.php: moodle_exception thrown
line 89 of /login/index.php: call to auth_plugin_googleoauth2->loginpage_hook()

**Comment by mouneyrac** [comment]
Thanks for the report, I am using v2.2 so it works as you mention. I'll check and fix it for 2.8.

**Comment by digiteratech** [comment]
Hi mouneyrac,
What's the status on updating plugin to support  Facebook API v2.8.

**Comment by mouneyrac** [comment]
it is working now see https://github.com/mouneyrac/moodle-auth_googleoauth2/issues/231
