### ISSUE TITLE
Facebook Login Broken 3-27-17

### ISSUE THREAD

**Issue by ahartzog** [mouneyrac/moodle-auth_googleoauth2#233]
I know this is a known issue per original author's post on the front, but I'm opening the issue so anyone else who suddenly has a broken Facebook login can discuss potential solutions here.

If anyone knows of a quick endpoint hotfix that can have this work temporarily while a long term fix is made, that would be extremely helpful.

**Comment by mouneyrac** [comment]
Thanks Alek for the report but I'll close it as duplicate as we have already #231 for it. 
Cheers,
Jerome
